---

- name: Install Docker dependencies
  apt: 
    name:
      - apt-transport-https
      - ca-certificates
      - curl 
      - software-properties-common


- name: Adding docker GPG key
  apt_key:
    url: "{{ docker_gpg_key }}"
    state: present
- name: Adding docker apt repository 
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present

- name: installing docker 
  apt: 
    name: docker-ce 
    state: latest
    update_cache: yes 

- name: Enabling and starting Docker service
  service: 
    name: docker
    state: started
    enable: yes 

- name: Allowing '{{ ansible_user }}' user to access Docker socket 
  user: 
    name: "{{ ansible_user }}"
    groups: docker 
    append: yes 

- name: Downloading docker-compose 
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_dest }}"
    mode: 0755